name: VuePress build and deploy
on:  
  push:
    branches: 
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: VuePress-Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: qcyblm/vuepress-theme-vpx
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn config set registry https://registry.npm.taobao.org/ && yarn && yarn docs:build
        BUILD_DIR: src/.vuepress/dist
