name: vuepress-deploy
on: 
  push:
    branches:
      - master
env:
  TZ: Asia/Shanghai
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node.js environment  ⚙️
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x
      - name: Install and Build 🔧
        run: |
          yarn
          yarn docs:build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: src/.vuepress/dist
          git-config-name: ${{ secrets.ACCESS_NAME }}
          git-config-email: ${{ secrets.ACCESS_EMAIL }}
          commit-message: "Deploy Production Code for Commit ${{ github.sha }}"
